server:
  port: 8082
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
  instance:
    prefer-ip-address: true