spring:
  application:
    name: spring-boot2-multi-redis-cache
  redis:
    timeToLive: 15
    lettuce:
      pool:
        MaxTotal: 50
        minIdle: 1
        maxWaitMillis: 5000
        maxIdle: 5
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
    redis-a:
      database: 7
      hostName: 192.168.96.24
      port: 16379
      timeout: 5000
    redis-b:
      database: 3
      hostName: ${spring.redis.redis-a.hostName}
      port: ${spring.redis.redis-a.port}
      timeout: ${spring.redis.redis-a.timeout}

