server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml


# 打印sql 语句
logging:
  level:
    top.lrshuai.mq.test.mapper.ShipmentMapper: debug

# mq
apache:
  rocketmq:
    namesrvAddr: 127.0.0.1:9876
    producer:
      producerGroup: planGroup
    consumer:
      PushConsumer: planConsumer

