server:
  port: 8081
spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
jwt:
  config:
    key: abc123
    ttl: 360000