emailplus:
  sender:
    qq01:
      host: smtp.qq.com
      port: 25
      username: 793272861@qq.com
      password: ENC(0Xn6xLVRo/JnOaY9e9RwtcFf2mKIw5tmB9W67pVCOR0=)
    vcredit01:
      host: smtp.263.net
      port: 25
      username: fkydssj@vcredit.com
      password: ENC(02Hz0uEM+qgrf08oQ6jWZuRSyUAga1Z/VyQ=)
    vcredit02:
      host: smtp.263.net
      port: 25
      username: huangchengkang@vcredit.com
      password: ENC(8nT5wqoL8qM4aft1L4A5/Qdc5b8e7uSsnBm5uRjEGAk=)
    vcredit03:
      host: smtp.263.net
      port: 25
      username: tangdandan@vcredit.com
      password: ENC(zXHzmOcN+6I8f1q7JP9cQ0rWW4b4f30StNc=)
  email-definitions:
    test-email:
      to: 793272861@qq.com
      subject: "系统测试测试"
      content: "ok"
      async: true
      html: true
    test-template:
      subject: 系统测试
      to: 793272861@qq.com
      template: hi.ftl
      data:
        name: emma
  email-notices:
    test-email-notice:
      capacity: 3
      trigger: redisPollingCountEmailNoticeTrigger
      email-key: test-template
      async: true
    test-email-notice2:
      capacity: 3
      refillTokens: 2
      refillDuration: PT5S
      trigger: redisBucketEmailNoticeTrigger
      email-key: test-template
      async: true
