spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml


# 打印sql 语句
logging:
  level:
    top.lrshuai.plus.springbootmybatisplus.test.mapper.ShipmentMapper: debug

