spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test1
      auto-offset-reset: earliest


datasource:
  read-size: 1
  master:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 20
    min-idle: 2
    filter:
      stat:
        enabled: true
  slave-alpha:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 20
    min-idle: 2
    filter:
      stat:
        enabled: true

