server:
  port: 8083
security:
  oauth2:
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8081/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://127.0.0.1:8081/user